name: CI Build

on:
  push:
    branches:
      - 'main'
      - 'hotfix/**'

    paths-ignore:
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Upload unit-test report
        uses: actions/upload-artifact@v3
        with:
          name: unit-test
          path: build/reports/tests/unit-test/aggregated-results
        if: always()

      - name: Upload test coverage report
        uses: actions/upload-artifact@v3
        with:
          name: test-coverage
          path: build/reports/jacoco/testCodeCoverageReport
        if: always()

      - name: Build application Docker image
        run: ./gradlew bootBuildImage

      - name: Print project version
        id: get-version
        run: |
          ./gradlew properties --console=plain | grep "version:" | awk -F': ' '{ print "::set-output name=VERSION::" $2; }'

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/alexandernikiforov/balanza-app
          tags: |
            type=sha,prefix=
            type=ref,event=branch

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: balanza-app
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # see https://github.com/docker/build-push-action/issues/755
          provenance: false

